---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debian-slim
  # allow for override: kubectl -n <ns> apply ...
  #namespace: default
spec:
  selector:
    matchLabels:
      app: debian-slim
  # kubectl scale --replicas=x deployment/debian-slim
  replicas: 1
  template:
    metadata:
      labels:
        app: debian-slim
      annotations:
        sidecar.istio.io/inject: "false"
    spec:

      # scaled up deployment will go to different nodes
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - debian-slim
            topologyKey: "kubernetes.io/hostname"

      containers:
      - name: debian-slim
        image: fabianlee/docker-debian-bullseye-slim-ntpclient:1.0.0
        args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; while [ 1 -eq 1 ]; do echo "infinite 10 second loop..."; sleep 10; done

        # resource limits
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m" # half vcpu
          limits:
            memory: "1024Mi"
            cpu: "1000m" # one vcpu

        env:
        # currently no env vars used for this container
        - name: FOO
          value: bar

        # check for lifetime liveness, restarts if dead
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 10

        # check for initial readiness
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 3
          periodSeconds: 3

      restartPolicy: Always
      #dnsPolicy: ClusterFirst
